### ISSUE TITLE
[Discussion] Improve mapping configuration for a better log search experience

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3296]
While testing our Grafana plugin, I went though a few frustrating cases:

I indexed most of the fields in a schemaless manner. Everything worked fine but:

- I was not able to search on a long UID. This is due to the fact the default tokenizer will omit tokens longer than 40 bytes.
- I was not able to search on UID with "-" separator. This is annoying especially when you are able to make an aggregation on the untokenized version.
- Same story on IP and several fields where you have short name that contains a character that is not a number nor a letter.

It seems the right dynamic setup is to not tokenize text by default, and on very specific field tokenize the text. And on this specific field, you want to set `fast: false`.

I would change the default tokenizer and raise the max token length to `255` bytes as done in elasticsearch.

- [ ] Raise max token limit to 255  (#3372)
- [ ] Make static mapping of object in array possible (#3371)
- [ ] Interpret implicit phrase queries as an intersection when position are not available (#3364)
- [ ] Set the default tokenizer for json & dynamic stuff to raw (#3373)

**Comment by fulmicoton** [comment]
> I was not able to search on UID with "-" separator. This is annoying especially when you are able to make an aggregation on the untokenized version.

For confirmation:
When you run the query using the normal search UI the spec is that it should run as a phrase query...
Did you receive an error message saying positions where not indexed and hence phrase query cannot?
Should we run those as intersection?

**Comment by fmassot** [comment]
> Did you receive an error message saying positions where not indexed and hence phrase query cannot?
Yes I did, and this was frustrating. Running those as intersections can improve the UX.

**Comment by fulmicoton** [comment]
I added a bunch of concrete actions and created separate tickets for each them. I need your input on #3371 @fmassot

**Comment by guilload** [comment]
This issue also demonstrates the need for a "log" tokenizer that would be better at identifying dates, IPs, and UUIDs. I'm adding #1143 to the 0.7 project.

**Comment by fulmicoton** [comment]
Closing as everything is tracked in other issues.
